# Generated by Django 2.1 on 2019-07-02 13:10

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('meta_tagger', '0003_auto_20181108_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatagpageextension',
            name='og_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.FILER_IMAGE_MODEL, verbose_name='Open Graph image'),
        ),
    ]
